name: 'TMFS Scan'

on:
  push:
  workflow_dispatch:

env:
  DIR: files
  

jobs:
  container-scan:
      name: TMFS Scan
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TMFS Scan
        run: |
          curl https://gist.githubusercontent.com/felipecosta09/dc3fd15f3a23a56e677b7c3436c3db47/raw/f2fbd6e6f9ede364d496b49f22774e3b49ca2ca6/tmfs_install.sh | bash
          # cd install
          # ls
          # chmod +x tmfs_install.sh
          # ./tmfs_install.sh
          export TMFS_API_KEY=${{ secrets.TMFS_API_KEY }}
          tmfs scan dir:${{ env.DIR }} -a > result.json
          cat result.json
      - name: 'Upload Scan Result Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: scan-result
          path: tmas/result.json
          retention-days: 30
